## Session 1: Into to Data Science

### Python Basics: Types, Expressions and Variables, String Operations

In [4]:
## Types and Variables
# Exercise 1
num1 = 10
num2 = 5
print(num1 + num2)

# Exercise 2
float_num = 3.14
print(type(float_num))

# Exercise 3
is_student = True
if is_student:
    print("The person is a student")
else:
    print("The person is not a student")


15
<class 'float'>
The person is a student


In [6]:
## String Operations
# Exercise 4
name = "Your Name"
print("Hello, " + name + "!")

# Exercise 5
str1 = "Hello"
str2 = "World"
print(str1 + " " + str2)

# Exercise 6
sentence = "Data Science is interesting!"
print(len(sentence))

# Exercise 7
extracted_word = sentence[11:17]
print(extracted_word)

# Exercise 8
updated_sentence = sentence.replace("interesting", "fascinating")
print(updated_sentence)

Hello, Your Name!
Hello World
28
e is i
Data Science is fascinating!


In [7]:
## Expressions
# Exercise 9
result = (5 * 3) + (2 ** 2)
print(result)

# Exercise 10
radius = 5
area_of_circle = 3.14 * (radius ** 2)
print(area_of_circle)

# Exercise 11
a = 10
b = 3
integer_division_result = a // b
remainder_result = a % b
print("Integer Division:", integer_division_result)
print("Remainder:", remainder_result)

# Exercise 12
area_integer = int(area_of_circle)
print(area_integer)

19
78.5
Integer Division: 3
Remainder: 1
78


### Python Data Structures: Lists and Tuples, Sets, Dictionaries

In [8]:
## Lists and Tuples
# Exercise 1
fruits = ["apple", "orange", "banana"]
print(fruits)

# Exercise 2
fruits.extend(["grape", "kiwi"])
print(fruits)

# Exercise 3
numbers = (1, 2, 3)
print(numbers)

# Exercise 4
print(numbers[1])

['apple', 'orange', 'banana']
['apple', 'orange', 'banana', 'grape', 'kiwi']
(1, 2, 3)
2


In [9]:
## Sets
# Exercise 5
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
print("Set 1:", set1)
print("Set 2:", set2)

# Exercise 6
intersection_set = set1.intersection(set2)
print("Intersection Set:", intersection_set)

# Exercise 7
set1.add(7)
set2.remove(3)
print("Updated Set 1:", set1)
print("Updated Set 2:", set2)

Set 1: {1, 2, 3, 4}
Set 2: {3, 4, 5, 6}
Intersection Set: {3, 4}
Updated Set 1: {1, 2, 3, 4, 7}
Updated Set 2: {4, 5, 6}


In [10]:
## Dictionaries
# Exercise 8
person = {"name": "John", "age": 30, "city": "New York"}
print(person)

# Exercise 9
print("Age:", person["age"])

# Exercise 10
person["occupation"] = "Engineer"
print("Updated Person:", person)

# Exercise 11
people_list = [
    {"name": "Alice", "age": 25, "city": "London"},
    {"name": "Bob", "age": 35, "city": "Paris"},
    {"name": "Charlie", "age": 28, "city": "Berlin"}
]
print("List of People:", people_list)

{'name': 'John', 'age': 30, 'city': 'New York'}
Age: 30
Updated Person: {'name': 'John', 'age': 30, 'city': 'New York', 'occupation': 'Engineer'}
List of People: [{'name': 'Alice', 'age': 25, 'city': 'London'}, {'name': 'Bob', 'age': 35, 'city': 'Paris'}, {'name': 'Charlie', 'age': 28, 'city': 'Berlin'}]


### Python Programming Fundamentals: Conditions and Branching, Loops, Functions, Objects and Classes

In [11]:
## Conditions and Branching
# Exercise 1
number = int(input("Enter a number: "))
if number > 0:
    print("Positive")
elif number < 0:
    print("Negative")
else:
    print("Zero")

# Exercise 2
number = int(input("Enter a number: "))
if number % 2 == 0:
    print("Even")
else:
    print("Odd")

Enter a number: 3
Positive
Enter a number: 0
Even


In [12]:
## Loops
# Exercise 3
for i in range(1, 6):
    print(3 * i)

# Exercise 4
sum_numbers = 0
counter = 1
while counter <= 10:
    sum_numbers += counter
    counter += 1
print("Sum:", sum_numbers)

3
6
9
12
15
Sum: 55


In [15]:
## Functions
# Exercise 5
def square(num):
    return num ** 2

# Exercise 6
def is_prime(num):
    if num < 2:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

print("Square value of ", 4, "is", square(4))
print("is 5 a prime number?", is_prime(5))

Square value of  4 is 16
is 5 a prime number? True


In [17]:
## Classes and Objects
# Exercise 7
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

# Exercise 8
    def greeting(self):
        print(f"Hello, my name is {self.name} and I am {self.age} years old.")

# Exercise 9
person1 = Person("John", 25)
person1.greeting()

Hello, my name is John and I am 25 years old.


In [20]:
# Exercise 10
class Rectangle:
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

## TO-DO
# Create an instance/object of Rectangle class
# Print the area and the perimeter of that object

<b>To-Do Exercise:</b>
Write a Python program that does the following:

1. Takes a user's name as input.

2. Checks if the name is longer than 5 characters. If yes, print "Long name." If no, print "Short name."

3. Asks the user to enter their age.

4. Checks if the age is greater than or equal to 18. If yes, print "You are eligible." If no, print "You are not eligible."

5. Uses a loop to print the squares of numbers from 1 to 5.

6. Defines a function named calculate_area that takes the length and width of a rectangle as arguments and returns the area. Call this function with length=4 and width=6 and print the result.

7. Creates a class named Car with attributes make and model. Initializes an object of the class with the make "Toyota" and model "Camry." Print the make and model.

8. Adds a method to the Car class named start_engine that prints "Engine started." Call this method on the car object.

9. Uses the is_prime function from a previous exercise to check if the user's age is a prime number. If yes, print "Prime age." If no, print "Not a prime age."

### Numerical Computition with NumPy

In [21]:
# Importing the numpy library, if it is not installed, check: https://numpy.org/install/
import numpy as np

In [22]:
import numpy as np

# Basic NumPy Operations:
# Exercise 1
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

# Exercise 2
zeros_array = np.zeros(10)
ones_array = np.ones(10)
print("Zeros Array:", zeros_array)
print("Ones Array:", ones_array)

# Exercise 3
equally_spaced_array = np.linspace(0, 1, 20)
print("Equally Spaced Array:", equally_spaced_array)

Addition: [6 6 6 6 6]
Subtraction: [-4 -2  0  2  4]
Multiplication: [5 8 9 8 5]
Division: [0.2 0.5 1.  2.  5. ]
Zeros Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Ones Array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Equally Spaced Array: [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [23]:
# Linear Algebra with NumPy:
# Exercise 4
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Multiplication:", matrix_product)

# Exercise 5
v = np.array([1, 2, 3])
m = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
dot_product = np.dot(v, m)
print("Dot Product:", dot_product)

Matrix Multiplication: [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Dot Product: [48 54 60]


In [24]:
# Statistical Operations:
# Exercise 6
random_array = np.random.randn(100)
mean_value = np.mean(random_array)
std_deviation = np.std(random_array)
variance = np.var(random_array)
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)
print("Variance:", variance)

# Exercise 7
data = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])
median_value = np.median(data)
mode_values = np.unique(data)[np.argmax(np.unique(data, return_counts=True)[1])]
print("Median:", median_value)
print("Mode:", mode_values)

Mean: -0.00773169048515805
Standard Deviation: 1.0321194017653723
Variance: 1.0652704595005102
Median: 3.0
Mode: 4


In [25]:
# NumPy Indexing and Slicing:
# Exercise 8
numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_numbers = numbers[3:8]
print("Sliced Numbers:", sliced_numbers)

# Exercise 9
numbers[5:10] = np.array([50, 51, 52, 53, 54])
print("Updated Numbers:", numbers)

Sliced Numbers: [3 4 5 6 7]
Updated Numbers: [ 0  1  2  3  4 50 51 52 53 54]


In [26]:
# Universal Functions (ufunc):
# Exercise 10
angles = np.array([0, np.pi/4, np.pi/2, 3*np.pi/4, np.pi])
sin_values = np.sin(angles)
cos_values = np.cos(angles)
tan_values = np.tan(angles)
print("Sine Values:", sin_values)
print("Cosine Values:", cos_values)
print("Tangent Values:", tan_values)

Sine Values: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
Cosine Values: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
Tangent Values: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


In [30]:
# Broadcasting:
# Exercise 11
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix += 10
print("Broadcasting - Added 10 to the Matrix:", matrix)

# Exercise 12
array = np.array([[1], [2], [3]])
result = matrix + array
print("Broadcasting - Added Array to Each Column of Matrix:", result)

Broadcasting - Added 10 to the Matrix: [[11 12 13]
 [14 15 16]
 [17 18 19]]
Broadcasting - Added Array to Each Column of Matrix: [[12 13 14]
 [16 17 18]
 [20 21 22]]


In [ ]:
## TO-DO Exercise
# Generate a random 2D array with shape 4 columns and 3 rows
random_2d_array = np.random.randint(1, 100, size=(?, ?))

# Display the generated array
print("Generated 2D Array:")
print(random_2d_array)

# Calculate mean, standard deviation, and median for each row
row_means = np.?
row_std_dev = np.?
row_medians = np.?

# Calculate mean, standard deviation, and median for each column
column_means = np.?
column_std_dev = np.?
column_medians = np.?

# Display the results
?

In [ ]:
## TO-DO Exercise

# Step 1
matrix_A = ?
matrix_B = ?

# Step 2
product_matrix = np.?

# Step 3
transposed_matrix = product_matrix.?

# Step 4
determinant_transposed = np.linalg.det(transposed_matrix)

# Display results
print("Matrix A:\n", matrix_A)
print("\nMatrix B:\n", matrix_B)
print("\nMatrix Product (A * B):\n", product_matrix)
print("\nTransposed Matrix:\n", transposed_matrix)
print("\nDeterminant of Transposed Matrix:", determinant_transposed)

### Data Manipulation with Pandas

In [7]:
# Importing the pandas library, if it is not installed, check: https://pandas.pydata.org/docs/getting_started/install.html
import pandas as pd

In [14]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)
#df.set_index('Name', inplace=True)

In [17]:
df.loc[3]

Name      David
Age          28
City    Chicago
Name: 3, dtype: object

In [18]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [19]:
df.isna().sum()

Name    0
Age     0
City    0
dtype: int64

In [42]:
print("Selected 'Age' column:")
print(df['Age'])

Selected 'Age' column:
Name
Alice      25
Bob        30
Charlie    35
David      28
Name: Age, dtype: int64


In [43]:
print("Filtered rows where 'Age' is greater than 30:")
print(df[df['Age'] > 30])

Filtered rows where 'Age' is greater than 30:
         Age         City
Name                     
Charlie   35  Los Angeles


In [44]:
df['Gender'] = ['Female', 'Male', 'Male', 'Male']
df.loc['Alice', 'City'] = 'Boston'

In [45]:
df.sort_values(by='Age', ascending=False, inplace=True)
print("DataFrame after sorting based on 'Age' in descending order:")
print(df)

DataFrame after sorting based on 'Age' in descending order:
         Age           City  Gender
Name                               
Charlie   35    Los Angeles    Male
Bob       30  San Francisco    Male
David     28        Chicago    Male
Alice     25         Boston  Female


In [46]:
grouped_by_city = df.groupby('City')
average_age_by_city = grouped_by_city['Age'].mean()
print("Average age for each city:")
print(average_age_by_city)

Average age for each city:
City
Boston           25.0
Chicago          28.0
Los Angeles      35.0
San Francisco    30.0
Name: Age, dtype: float64


In [47]:
data2 = {
    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago'],
    'Population': [8_398_748, 884_363, 3_979_576, 2_693_976]
}
df2 = pd.DataFrame(data2)
merged_df = pd.merge(df, df2, on='City')

In [48]:
df.loc['David', 'Age'] = np.nan
df['Age'].fillna(df['Age'].mean(), inplace=True)

In [49]:
pivot_table = pd.pivot_table(df, values='Age', index=['City', 'Gender'], aggfunc=np.mean)
print("Pivot Table - Average age for each combination of 'City' and 'Gender':")
print(pivot_table)

Pivot Table - Average age for each combination of 'City' and 'Gender':
                       Age
City          Gender      
Boston        Female  25.0
Chicago       Male    30.0
Los Angeles   Male    35.0
San Francisco Male    30.0


C:\Users\jairiidriss\AppData\Local\Temp\ipykernel_13148\2672783369.py:1: FutureWarning: The provided callable <function mean at 0x000002BC3F0AE700> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  pivot_table = pd.pivot_table(df, values='Age', index=['City', 'Gender'], aggfunc=np.mean)
